apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels: # this labels are deployment labels
    app: mongodb
    project: roboshop
    tier: db
  
spec:
  replicas: 1
  selector: 
    matchLabels: # this labels are used to find the pods
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # this labels are pod labels
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: dockerhub2009/mongodb:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017          


